export const metadata = {
  title: {
    default: 'Next.js | Hello world',
    template: '%s | Hello World',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-black">
          <p className="text-white" >Header</p>
        </header>
        {children}
        <footer className="bg-black">
          <p className="text-white" >footer</p>
        </footer>
      </body>
    </html>
  )
}
